swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login - HTML Injection
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Resilience PT</h1>
    </div>
    <div class="form-container">
        </form>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
